--- 
# tasks file for mongodb

- name: cleanup default 
  apt: 
    name: mongodb
    state: absent

- name: install mongodb 
  apt:
    name: mongodb
    state: latest
    update_cache: yes

- name: create data directory
  file:
    path: /data/db
    state: directory 
    owner: '{{ username }}'
    group: '{{ username }}'

- name: start mongod service 
  systemd: 
    name: mongodb
    state: started